development:
  adapter:  sqlite3
  database: db/development.sqlite3
  pool:     5
  timeout:  5000

test:
  adapter:  sqlite3
  database: db/test.sqlite3
  pool:     5
  timeout:  5000

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  username: <%= ENV['POSTGRES_DATABASE_USER'] %>
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DATABASE_NAME'] %>
