production: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  host:     db
  port:     5432
  username: postgres
  password:

development:
  <<: *default
  adapter:  sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter:  sqlite3
  database: db/test.sqlite3
